apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.postgres_namespace }}
spec:
  selector:
    app: {{ .Values.postgres_name }}
  ports:
    - protocol: TCP
      port: 5432  # Puerto en el servicio
      targetPort: 5432  # Puerto en el contenedor
  clusterIP: None  # Esto se puede modificar seg√∫n las necesidades de acceso
